Added damaging of turrent, enemy and player
JimmyC7834/U.group-party-game pull request #19
Opened 2023-02-26 08:10 UTC by JoelLei121

2023-02-26 08:22 UTC, JimmyC7834 requested changes

2023-02-26 08:22 UTC, JimmyC7834 commented on .vscode/settings.json
> +﻿{
remove this file

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Enemy/EnemyController.cs
> +            if (judgeNode != null)
try not to nest `if` because hard to read.
try this instead:
```c_sharp
if (judgeNode == null) return;
....
```

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Enemy/EnemyController.cs
> +            // bad calculation, fail when gen in node 0
Maybe need to revise this logic.
need to be fixed in other branch later

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Enemy/EnemyController.cs
> +        {
directly check the component is enough:
```
PlayerStats playerStats = collision.collider.GetComponent<PlayerStats>();
if (playerStats == null) return;
...
```

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Player/PlayerControl.cs
> +                // _stats.Killed += Kill;
try not to include commented code

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Player/PlayerControl.cs
> +            if (_stats != null)
what do you mean by getting the `PlayerStat` if there is a `PlayerStat` (`_stats != null`)?

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Turret/TurretBase.cs
> +                Destroy(this.gameObject, 1);
Return to pool instead of destroy the object

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Turret/TurretBase.cs
>              if (other.gameObject.layer == LayerMask.NameToLayer("Enemy"))
Same I suggest check the player component like the comment above

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Turret/Bullet/TurretBulletBase.cs
>              if (collider.gameObject.layer == LayerMask.NameToLayer("Enemy"))
Same I suggest check the player component like the comment above

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Turret/Bullet/GunTurretBullet.cs
> +            enemyStats?.Hit(_damage);
do not use `?.` in here because hard to read.
Instead:
```
if (enemyStats != null)
{
...
}
```

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/Stone.cs
> +            if (collider.gameObject.layer == LayerMask.NameToLayer("Enemy"))
Same I suggest check the player component like the comment above

2023-02-26 08:22 UTC, JimmyC7834 commented on Assets/Script/PoolObjectStatsBase.cs
> +            CheckHealth();
no need to separate into functions yet?

2023-03-01 08:00 UTC, JoelLei121 commented on .vscode/settings.json
> +﻿{
updated .gitignore

2023-10-06 02:59 UTC, merged